# Generated by Django 3.1.1 on 2020-10-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201023_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ptype',
            field=models.CharField(default='', max_length=30),
        ),
    ]
