# Generated by Django 3.1.1 on 2020-10-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201025_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ptype',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
