# Generated by Django 3.1.1 on 2020-10-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
