# Generated by Django 3.1.1 on 2020-11-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
